services:
    db:
        image: mysql:latest
        container_name: mysql_db
        command: '--default-authentication-plugin=mysql_native_password'
        restart: always
        hostname: mysql_db
        ports:
            - "3037:3036"
        env_file:
            - config.cnf
        tty: true
        networks:
            - mynet
        volumes:
            - mysqldata/var/lib/mysql
    airflow-engine:
        build: .
        container_name: airflow
        command: /bin/sh -c "/root/airflow/setup.sh"
        depends_on:
            - db
        init: true
        ports:
            - "192.168.0.2:8080:8080"
        environment:
            - PYTHONPATH=/root/airflow
        env_file:
            - config.cnf
        tty: true
        networks:
            - mynet
        volumes:
            - airflowdata/root/airflow/
networks:
    mynet:
volumes:
    airflowdata:
    mysqldata:
